/**
 * OpenApi specification - Social
 * OpenApi documentation for this cozy social  network project
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Like } from './like';
import { User } from './user';


export interface Post { 
    id?: number;
    author?: User;
    content?: string;
    likes?: Array<Like>;
    parent?: Post;
    replies?: Array<Post>;
    created_timestamp?: string;
    photoPaths?: Array<string>;
}

