/**
 * OpenApi specification - Social
 * OpenApi documentation for this cozy social  network project
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Token { 
    id?: number;
    token?: string;
    tokenType?: Token.TokenTypeEnum;
    expired?: boolean;
    revoked?: boolean;
    user?: User;
}
export namespace Token {
    export type TokenTypeEnum = 'BEARER';
    export const TokenTypeEnum = {
        Bearer: 'BEARER' as TokenTypeEnum
    };
}


