/**
 * OpenApi specification - Social
 * OpenApi documentation for this cozy social  network project
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Follow } from './follow';
import { Like } from './like';
import { Post } from './post';


export interface UserPrivateDto { 
    id?: number;
    username?: string;
    email?: string;
    role?: UserPrivateDto.RoleEnum;
    mfaEnabled?: boolean;
    likes?: Array<Like>;
    posts?: Array<Post>;
    follows?: Array<Follow>;
    followers?: Array<Follow>;
}
export namespace UserPrivateDto {
    export type RoleEnum = 'USER' | 'ADMIN' | 'MODERATOR';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Moderator: 'MODERATOR' as RoleEnum
    };
}


