/**
 * OpenApi specification - Social
 * OpenApi documentation for this cozy social  network project
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Follow } from './follow';
import { Like } from './like';
import { Post } from './post';


export interface UserPublicDto { 
    id?: number;
    username?: string;
    likes?: Array<Like>;
    posts?: Array<Post>;
    follows?: Array<Follow>;
    followers?: Array<Follow>;
}

