/**
 * OpenApi specification - Social
 * OpenApi documentation for this cozy social  network project
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Follow } from './follow';
import { Like } from './like';
import { Post } from './post';
import { GrantedAuthority } from './granted-authority';
import { Token } from './token';


export interface User { 
    id?: number;
    username?: string;
    email?: string;
    password?: string;
    mfaEnabled?: boolean;
    secret?: string;
    role?: User.RoleEnum;
    tokens?: Array<Token>;
    likes?: Array<Like>;
    posts?: Array<Post>;
    follows?: Array<Follow>;
    followers?: Array<Follow>;
    avatarPath?: string;
    enabled?: boolean;
    authorities?: Array<GrantedAuthority>;
    accountNonLocked?: boolean;
    credentialsNonExpired?: boolean;
    accountNonExpired?: boolean;
}
export namespace User {
    export type RoleEnum = 'USER' | 'ADMIN' | 'MODERATOR';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Moderator: 'MODERATOR' as RoleEnum
    };
}


