export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authentication.serviceInterface';
export * from './files.service';
import { FilesService } from './files.service';
export * from './files.serviceInterface';
export * from './follows.service';
import { FollowsService } from './follows.service';
export * from './follows.serviceInterface';
export * from './likes.service';
import { LikesService } from './likes.service';
export * from './likes.serviceInterface';
export * from './posts.service';
import { PostsService } from './posts.service';
export * from './posts.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AuthenticationService, FilesService, FollowsService, LikesService, PostsService, UsersService];
