/**
 * OpenApi specification - Social
 * OpenApi documentation for this cozy social  network project
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthenticationRequest } from '../model/models';
import { MfaToggleRequest } from '../model/models';
import { RegistrationRequest } from '../model/models';
import { VerificationRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Authentication
     * 
     * @param authenticationRequest 
     */
    authenticate(authenticationRequest: AuthenticationRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Generate QR-code for mfa
     * 
     */
    getMfaSetup(extraHttpRequestParams?: any): Observable<object>;

    /**
     * Auth token refresh
     * 
     */
    refreshToken(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * New user registration
     * 
     * @param registrationRequest 
     */
    register(registrationRequest: RegistrationRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Toggle on/off of mfa
     * 
     * @param mfaToggleRequest 
     */
    toggleMfa(mfaToggleRequest: MfaToggleRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Mfa code verification
     * 
     * @param verificationRequest 
     */
    verifyCode(verificationRequest: VerificationRequest, extraHttpRequestParams?: any): Observable<object>;

}
