/**
 * OpenApi specification - Social
 * OpenApi documentation for this cozy social  network project
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangePasswordRequest } from '../model/models';
import { UploadAvatarRequest } from '../model/models';
import { UserPrivateDto } from '../model/models';
import { UserPublicDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Change password
     * 
     * @param changePasswordRequest 
     */
    changePassword(changePasswordRequest: ChangePasswordRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Get private user data
     * 
     */
    getPrivateUserData(extraHttpRequestParams?: any): Observable<UserPrivateDto>;

    /**
     * Get public user data
     * 
     * @param username 
     */
    getPublicUserData(username: string, extraHttpRequestParams?: any): Observable<UserPublicDto>;

    /**
     * 
     * 
     * @param uploadAvatarRequest 
     */
    uploadAvatar(uploadAvatarRequest?: UploadAvatarRequest, extraHttpRequestParams?: any): Observable<string>;

}
